/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
              "surface-container-lowest": "#0c0e11",
              "on-error-container": "#ffdad6",
              "on-secondary-container": "#e5a9ff",
              "error": "#ffb4ab",
              "outline": "#849396",
              "secondary": "#e9b3ff",
              "on-primary": "#00363d",
              "on-surface-variant": "#bac9cc",
              "surface-container": "#1e2023",
              "surface-tint": "#00daf3",
              "on-primary-container": "#00626e",
              "tertiary-fixed": "#ffdf96",
              "primary-fixed": "#9cf0ff",
              "on-tertiary": "#3e2e00",
              "surface-dim": "#111316",
              "surface-variant": "#333538",
              "surface-container-high": "#282a2d",
              "on-background": "#e2e2e6",
              "on-tertiary-container": "#6f5500",
              "on-tertiary-fixed-variant": "#594400",
              "surface-container-highest": "#333538",
              "primary-fixed-dim": "#00daf3",
              "secondary-fixed": "#f6d9ff",
              "inverse-surface": "#e2e2e6",
              "on-secondary-fixed": "#310048",
              "tertiary-fixed-dim": "#f3bf26",
              "surface": "#111316",
              "on-secondary-fixed-variant": "#7200a3",
              "on-secondary": "#510074",
              "on-surface": "#e2e2e6",
              "primary-container": "#00e5ff",
              "secondary-fixed-dim": "#e9b3ff",
              "inverse-primary": "#006875",
              "on-tertiary-fixed": "#251a00",
              "inverse-on-surface": "#2f3034",
              "outline-variant": "#3b494c",
              "background": "#111316",
              "on-error": "#690005",
              "on-primary-fixed": "#001f24",
              "surface-bright": "#37393d",
              "tertiary-container": "#fec931",
              "tertiary": "#ffeac0",
              "error-container": "#93000a",
              "surface-container-low": "#1a1c1f",
              "on-primary-fixed-variant": "#004f58",
              "secondary-container": "#7d01b1",
              "primary": "#c3f5ff"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"],
      },
      backdropBlur: {
        xs: '2px',
      }
    },
  },
  plugins: [],
}
